csv2counter.py
引数 `--place` ありの実行例です。
```
(fgosccnt) vagrant@ubuntu-eoan:/vshare/github/fgosccnt$ ./csv2counter.py result_20200328_1.csv --place "テスト撃退戦 テスト級"
【テスト撃退戦 テスト級】30周
胆石5-鉄杭20
槍モ21-槍ピ6
コイン(+3000)53-コイン(+6000)30-チョーク(x3)300-チョーク(x5)55
QP(+500000)28-QP(+520000)30-QP(+400000)16-QP(+300000)10
経験値礼装3-城塞の午後1
#FGO周回カウンタ http://aoshirobo.net/fatego/rc/
```
引数なしの場合は従来と同じです。
```
(fgosccnt) vagrant@ubuntu-eoan:/vshare/github/fgosccnt$ ./csv2counter.py result_20200328_1.csv
【周回場所】30周
胆石5-鉄杭20
槍モ21-槍ピ6
コイン(+3000)53-コイン(+6000)30-チョーク(x3)300-チョーク(x5)55
QP(+500000)28-QP(+520000)30-QP(+400000)16-QP(+300000)10
経験値礼装3-城塞の午後1
#FGO周回カウンタ http://aoshirobo.net/fatego/rc/
```
その他:
変数名 `skilstone_list` と `skillstone_list` が混在していたので、後者にそろえておきました。
=> csv2counter 周回場所を実行時オプション --place で指定可能にする

fgosccnt.py
二行目のアイテムが認識されずに三行目のアイテムのみが認識されるケースが一つだけあったのでそれに対応した修正
=> 画像認識位置が一行ずれるバグの修正

csv2counter.py, fgosccnt.py, hash_drop.json
- dropPriorityをアイテム順のソートに使用
- スキル石・モニュピより優先度の低いdropPriorityのアイテムを認識したら以降スキル石・モニュピを認識対象から外し、誤認識を防止
- csv2counterもJSONデータを参照するように
=> dropPriority対応 csv2counterの改修

csv2counter.py, data/json/jikenbo.json, data/json/ooku.json, data/json/requiem.json, data/json/saberwars2.json, data/json/xmas2018.json, data/json/xmas2019.json, fgosccnt.py, freequest.json, syurenquest.json
クエスト名が判定できるようになった
判定に成功した場合、出力の「合計」の位置にクエスト名が出る
JSONはfgosccalcと同一
=> クエスト名判定機能の実装

csv2counter.py
csv2counter.py の実行時、クエスト名が自動認識されない場合【周回場所】とでなければいけないところが【合計】となっていたバグを修正
=> 周回場所が合計とでるバグ修正

data/json/cbc2019.json, data/json/cbc2020.json, data/json/valentine2018.json, data/json/valentine2019.json, data/json/valentine2020.json, hash_drop.json, make_hash_battle.py
1. 現時点で[未復刻イベント一覧](https://gamewith.jp/fgo/article/show/154578)にでているバトルリザルトのスクショが必要になるイベントは「激闘！クラス別サーヴァント戦」を除き収録した
2. item/ ディレクトリ以下にできるPNGファイルのハッシュ値を回収する make_hash_batlle.py を新規追加した
=> 未復刻イベント対応とハッシュ値回収プログラムの追加

fgosccnt.py
全ての種火〰大火を除外しなければいけない部分が、all種火・all灯火・all大火のみが除外される設定になっていたのを修正
=> クエスト名認識時の種火設定ミスを修正

fgosccnt.py, requirements.txt
重複チェック機能の追加
- tesseract-OCR のインストールが必要
- pytesseract が依存ライブラリに追加
以下のものを重複ファイルとして dupilcate と出してアイテム数は出さない
- (QPカンストしていない場合)QPが同じで同じドロップアイテムファイル
- (QPカンストしている場合)同じドロップアイテムで15秒以内に作成されたファイル
=> Duplicate enhanement

fgosccnt.py
NA version PNG difference from JP version PNG, so NA version don't use PNG routine.
=> for NA version PNG fix

fgosccnt.py
1. The part that recognizes the bonus in PNG was enbuged, so that's fixed. Changed the NA version back to use the original routines for PNGs.
2. Return (drop_count)-1 if there is something that is overlay non-number object for the drop count in the upper right corner of the screenshot.
3. The correct item is recognized even if drop_count is -1.
1. PNGでボーナスを認識する箇所がエンバグしていたので修正。NA版を元のPNG用ルーチンを使うように戻した
2. スクリーンショットの右上のドロップ数にオーバーレイする数字でない何かがある場合、(drop_count)-1を返すようにした
3. drop_count　が-1の場合でも正しいアイテムを認識するようにした
=> Unrecog bug fix

fgosccnt.py
`pageinfo.detect_qp_region()` が失敗した場合に `None` が返されますが、この際に処理を継続せずに QP が読み取れなかったことを示す `-1` を返すようにします。
`pageinfo.detect_qp_region()` returns `None` if it fails to detect. In that case, caller returns `-1` that means QP detection failure, instead of performing following process.
=> improve QP detection Handling

fgosccnt.py
#183 の修正
#181 の修正で、class ScreenShotは複数ページで構成されるスクショのアイテムの重複除去をしなくなり、get_output()内で行うようにしたが、duplicateの判定時、重複を除去した前の頁のアイテムと重複を除去しない現在の頁のアイテムを比較していたためduplicateと出力されなくなっていた
=> 前の頁の重複したアイテムをカットするタイミングの間違い

fgosccnt.py
if pageinfo return None for total qp pt, use hard cord pt.
It is close to the capy-drop-parser coordinates
=> if pageinfo return None for qp pt, use hard cord pt

fgosccnt.py, pageinfo.py
- Improved item recognition rate.
- Use the previous id, category, and name if the previous item is a close phash
- (non-point, non-QP items) Once a bonus is recognized, the same item uses the same bonus
- teseract-OCR is slow, so it is used only when pageinfo fails to recognize
- Reward The last digit of QP is set to 0 determinism, and the last two digits of QP and Point are set to 00 determinism.
----
- アイテムの認識率を改善した
- 前のアイテムが近いphashだったらそのid, categry, nameを使う
- (point, QP以外のアイテム)ボーナスを一度認識した場合、同じアイテムは同じボーナスを使う
- teseract-OCRは遅いのでpageinfoが認識失敗した場合にのみ使用するようにした
- Reward QPの下一桁は0決め打ち、QPとPointの下二桁は00決め打ちにした
=> Performance Improvement

fgosccnt.py
- switched to using the logger completely, so the -d option is gone. Use --loglevel debug instead
- Faster speeds using template matching to reduce the number of times the SVM is used
----
- 完全にloggerを使うようにしたので-dオプションは廃止。代わりに --loglevel debug を使用すること
- テンプレートマッチングを使用して、SVMの使用回数を減らした高速化
=> Removal  of the -d option and speeding up

fgosccnt.py
If detection of a straight line from the top of the scrollbar fails, it is detected from the bottom of the scrollbar.
=> fix cutting gamescreen

fgosccnt.py
add phash_narrow in fgoscdata to the case where CE is scrolling and partially disappearing.
概念礼装がスクロールして一部消えているケースにfgoscdata で phash_narrow を加えて対応
=> CE scrolled down case fix

fgosccnt.py
- Bug fix for judging QP as Reward QP
- There were cases where the cash wasn't working.
- Pieces and monuments are now differentiated by background, so they're cacheable.
=> Bug fix for judging QP as Reward QP

fgosccnt.py
In the following images, 1 and 7 cannot be detected in drop_num, total_qp and gained_qp because of the threshold.
=> Changing the threshold

fgosccnt.py
If pageinfo throws a TooManyAreasDetectedError exception, process to return the corrected result added
=> Page noreturn fix

fgosccnt.py
イベントクエストで概念礼装EXPカードがドロップしているとき、概念礼装がドロップしていないにも関わらず礼装0がでないバグを修正
=> 礼装0がでないバグを修正

fgosccnt.py
Fixed a bug in the new UI that caused the information window to misidentify an item as having an item when there was no item to cover in the first line
=> bug fix for information window in New UI

fgosccnt.py
https://fgojunks.max747.org/fgosccnt/results/e4df4a60-8cd8-4285-833f-37780b1ae80f/
で破線の判定に失敗するため not valid になる問題の修正
=> fix line detection for broken line

fgosccnt.py
16;9スクリーンのときのみOCRのドロップ数読み込み範囲を狭め誤認識を抑制するよう修正
=> fix dcnt OCR (16:9 screen only)

fgosccnt.py
https://fgojunks.max747.org/fgosccnt/results/fbf9232b-c6f8-4f1d-ac09-3424b8450c8e/
のnot validの解消
=> fix ocr_dcnt

fgosccnt.py
情報ウィンドウがある場合の「獲得した戦利品」の下の破線検出を情報ウィンドウの右側でもできるよう修正
=> fix broken line

fgosccnt.py
直線を誤検知してgamescreenの高さが足りなくなった場合、再定義してエラーを回避
=> fix bottom_y detection

fgosccnt.py
一行目アイテム下部に稀に背景のキャラクターと重なって直線ができてしまうため、
それより上の位置をとるよう修正
新旧UIに対応
=> 一行目アイテム下部に稀にできる直線避け

fgosccnt.py
ノッチ検出の閾値を0.9から0.7まで下げないとエラーになるスクショが存在するので下げることに
=> fix notch threshold

qpsplit.py
環境が変わったりバージョンアップするたびに`Qp_dir = f.parent / Qp_dir`と変更をして利用していたのですが、大変になってきたため、取り込んでいただけたら嬉しいです。
元の動作には影響がない追加になっていると思います。
ご検討のほどよろしくお願いいたします。
=> add options to specify the output destination directory of qpsplit.py

fgosccnt.py
The area was not checked when detecting the game screen.
This caused a problem when an area with the same ratio was detected by chance, which has been fixed.
=> Added an area check to the game screen

fgosccnt.py
#310 の修正
理由は不明だが、通常のゲームスクリーンの外側にもう一つの領域検出してしまうので、高さで制限をかけることにして除外する
=> 誤検知するゲームスクリーンを除去

pageinfo.py
ゲーム画面の新旧判定において `cv2.matchTemplate()` で例外が発生した場合は、常に新画面として扱うこととしました。
=> update pageinfo.py to the latest

pageinfo.py
スクロールバー候補矩形の頂点数が多すぎる場合は不適とするフィルターを追加しました。
閾値の妥当性については、今後実績を積み重ねていく中でパラメーターを調整していきます。とりあえず閾値 150 で手元のテストはすべて通ります。誤検出した画像 image3.jpeg の頂点数は 516 でした。
=> update pageinfo to the latest

pageinfo.py
右端が黒背景のクエストで右端がカットされてしまいスクロールバー検出に影響してしまう不具合に対処する。
=> update pageinfo to the latest version

csv2counter.py
```
$ ./csv2counter.py result.csv
###############################################
###############################################
22行目に missing (複数ページの撮影抜け)があります
41行目に missing (複数ページの撮影抜け)があります
44行目に missing (複数ページの撮影抜け)があります
99行目に missing (複数ページの撮影抜け)があります
138行目に missing (複数ページの撮影抜け)があります
###############################################
【第三関門 ザ・マッシュルーム】100周
礼装0
炉心28
証54
狂秘13
狂輝21
騎モ2
術モ1
殺モ6
狂モ9
手形(x3)529
手形(x4)722
水鉄砲(x3)728
水鉄砲(x4)416
プロテクター(x4)208
#FGO周回カウンタ http://aoshirobo.net/fatego/rc/
証泥UP %
```
これを JSON で出力した場合でも同様に warning が含まれるように改修する。
`has_warnings` と `warning_messages` が増えている。
```
$ ./csv2counter.py --json result.csv
{
"questname": "第三関門 ザ・マッシュルーム",
"runs": 100,
"lines": [
{
"material": "礼装",
"initial": 0
},
{
"material": "炉心",
"initial": 28
},
...(snip)...
{
"material": …
```
=> csv2counter: json フォーマットに警告メッセージを含める
