fgosc/fgosccnt

fgosccnt.py

画面中央から右端のラインを探すところを、画面3/4の位置から探すよう変更

Fix gamescreen triming bug

---

fgosccnt.py

requiem イベントでライフカウンターのボーナス文字認識に失敗する問題解決

---

fgosccnt.py

ドロップ数7のとき情報ウィンドウとかぶるとおかしくなるのを修正他

---

fgosccnt.py
qpsplit.py
qpsplit_gui.py

・GUI版qpsplit qpsplit_gui.py の追加とそれに伴うqpsplit.py fgosccnt.py の修正
・低解像機のQP6桁ボーナスバグのフィックス #57

低解像機のQP6桁ボーナスバグのフィックス

---

fgosccnt.py

OCR誤認識によりNull Charが出力されていることによりcsv2counterが正常終了しないバグの修正

Null Char の出力抑制

---

fgosccnt.py

ファイル名が
```
IMG_9998.png
IMG_9999.png
IMG_0001.png
IMG_0002.png
...
```
のような連番のケースで、ファイル名の順で処理すると 9999 と 0001 が接続せず、これらが連続するスクリーンショット群を構成する場合に missing を引き起こす。ファイルの作成日時順で処理すればこの問題は回避できる。
この Pull Request ではソート順を指定するオプションを加え、ファイル作成日時によるソートを可能とする。ただしオプションを指定しない場合のデフォルトはこれまでの動作と変わらないようにする。

ファイルのソート順を指定するオプションを追加。

---

fgosccnt.py

#65 への対応
ドロップの認識方法を変更
7桁→6桁→1-5桁と順に読み込み、失敗しなかったらその数値を採用するfgosccalcと同じ認識方式

QP7桁認識バグフィックス

---

fgosccnt.py

閾値を厳しくしすぎて認識エラーがでるファイルができてしまったので修正

fix #68 (再)

---

fgosccnt.py

Reisou0 add

---

fgosccnt.py
qpsplit.py

- #85 対応
- JPEGファイル読み込みに対応
- FGO NA Version のバトルリザルトのスクショに対応

JPEG read & FGO NA version

---

fgosccnt.py

fix #43 and #95

---

fgosccnt.py

fix #97 #98

---

fgosccnt.py

fix #120 again

---

fgosccnt.py
qpsplit.py

qpsplitの非互換による動作不能を修正

---

fgosccnt.py

daat/ 以下にできた画像ファイルの名称tと同じものが json 内にある場合、そのidとdropPriorityを使用するように変更

local itemの扱い変更

---

.gitmodules
fgosccnt.py

初回のみ、以下を実行する必要があります。
```
git submodule update --init
```
以降は fgoscdata の更新を取り込むときに
```
git submodule update --remote
```
で参照するsubmoduleが更新されますので、これを
```
git add fgoscdata
```
あとは commit して push するいつもの流れです。
submodule の状況を確認したければ
```
cd fgoscdata
git log
```
などでコミット履歴を確認することができます。

fgoscdataをsubmoduleに追加。

---

pageinfo.py

所持 QP 領域の検出が必要になるかもしれないので、実装を再検証したところいろいろと不備が見つかったので全面的に見直しした。

pageinfo を更新。QP 検出処理をリライト。

---

fgosccnt.py

add debug info

---

fgosccnt.py

- Modify: time を使用するように
- 比較式にバグがあったので修正

change ctime to mtime and bugfix

---

csv2counter.py

duplicate があった場合、csv2counter で警告を出すようにした

csv2counter の duplicate 対応

---

fgosccnt.py

QPカンスト時の重複チェック時間をオプション指定可能に

---

fgosccnt.py

fix no exif bug

---

fgosccnt.py

複数ファイルを処理した場合、再びexifがあるファイルが出現したときnot valid になる不具合を修正

fix no exif bug again

---

pageinfo.py

pageinfo を最新にする。

---

fgosccnt.py

Fixed a warning on lint

---

fgosccnt.py

Lint code fix

---

pageinfo.py

ref: 
- https://github.com/fgosc/pageinfo/pull/1
- https://github.com/fgosc/pageinfo/pull/2

update pageinfo to the latest version

---

pageinfo.py

update pageinfo.py to the latest that has fixed a problem https://github.com/fgosc/pageinfo/pull/4

update pageinfo.py to the latest version

---

fgosccnt.py

Use --lang eng option to output in English
or in the source code:
```DEFAULT_ITEM_LANG = "jpn"```
chenge to
```DEFAULT_ITEM_LANG = "eng"```
New item English names that are not in the game api are not supported.

Added --lang option to output in English

---

fgosccnt.py

Fixed a bug that prevented the item from being recognized after failing to recognize the card type
カード種別認識に失敗したとき以降のアイテムが認識されないバグの修正

Item misrecognition bug fix

---

fgosccnt.py

- Fixed phash_narrow doesn't support reading from templace
- Fixed not using phash_narrow
- Fixed that drop_num does not match in --lang eng
----
- phash_narrow が templace からの読み込みに対応していなかったのを修正
- phash_narrow を使用していなかったのを修正
- --lang engでdrop_numが合っていかなったのを修正

fix scrolled CE

---

pageinfo.py

in order to fix #201 by https://github.com/fgosc/pageinfo/pull/5

updage pageinfo.py to the latest

---

pageinfo.py

to merge changes https://github.com/fgosc/pageinfo/pull/6

update pageinfo.py to the latest

---

fgosccnt.py

Check qp_gained and guestnum to check missing strictly

check missing file

---

fgosccnt.py

pageinfoがスクロールバー取得に失敗したときに正しいスクロールバーの位置を返す

fall back when pageinfo fail

---

qpsplit.py

引数のミスマッチを修正

---

csv2counter.py

https://fgojunks.max747.org/fgosccnt/results/e0e1db9e-1e08-41e0-a84c-29d71a0d31f6/
```
[CRITICAL] dropの取得に失敗
```
とでてcsv2counterの結果が出力できないバグの修正

csv2counter.py fix for freequest & syurenquest bug

---

fgosccnt.py

https://fgojunks.max747.org/fgosccnt/results/e03d1ab2-f060-4ed8-86b0-75e7834a5a54/
の警告修正

fix for e03d1ab2-f060-4ed8-86b0-75e7834a5a54

---

fgosccnt.py

fix gamescreen bug for
https://fgojunks.max747.org/fgosccnt/results/fc2cd14d-3bf2-4a93-917a-4a81f82b4e2f/

fix for fc2cd14d-3bf2-4a93-917a-4a81f82b4e2f

---

fgosccnt.py

Fixed wrong coordinates to get in fall back when pageinfo.py fails to fall back in New UI.

fix qp fallback fail for New UI

---

fgosccnt.py

Fixed failure to recognize two-digit numbers.

New UI drop_count fix

---

csv2counter.py
fgosccnt.py

csv2counter.pyでitem???を処理したときにエラーにならないよう修正

item??? file fix

---

fgosccnt.py

https://fgojunks.max747.org/fgosccnt/results/49a079f3-94e8-4b01-a33c-c8680bdbb985/
で item??? ができてしまうバグの修正

fix item border detection bug

---

fgosccnt.py

remove code

---

fgosccnt.py

https://fgojunks.max747.org/fgosccnt/results/49a079f3-94e8-4b01-a33c-c8680bdbb985/ の出力修正

fix 49a079f3-94e8-4b01-a33c-c8680bdbb985

---

fgosccnt.py

Fixed a bug where straight lines outside gamescreen were recognized.

fix for widescreen

---

fgosccnt.py

直線検出を緩くした結果余分な直線ができるためgamescreenの右x検出に失敗するので、ノッチを除いたgamescreenの中心を求め、左xの位置からほぼ正確な右xを推定するように修正

fix 95a48e72-17a4-4b15-b081-419eab7eddb9

---

fgosccnt.py

fix not valid in https://fgojunks.max747.org/fgosccnt/results/ff21fbef-8fee-4334-8016-a2530436e0ae/

fix ff21fbef-8fee-4334-8016-a2530436e0ae

---

csv2counter.py

csv2counter.py でクエスト名が序破急のとき追加出現率 % が末尾につくようにした

序破急のクエストに追加出現率を加えた

---

fgosccnt.py

Fix gamescreen

---

fgosccnt.py

品質80でJPEG化した画像が not validとなる問題で、元画像からゲームスクリーン検出を2回行っていて2回目の検出で1回目と異なる座標を出力している問題が発覚
検出は1回だけとし、そのとき検出した座標を使用することとして対策した

Fixed the game screen coordinate judging to once instead of twice

---

fgosccnt.py

pass すると fileoutput.append(output) されてしまうので continue で次のループに行く。

---

csv2counter.py
fgosccnt.py

add missing item recognition

---

fgosccnt.py

追加ドロップの認識修正

---

fgosccnt.py

報酬QP読み取りバグ修正

---

csv2counter.py

ファイルからの読み込み時にBOM付UTF-8が指定されないバグを修正

fix encoding bug

---

fgosccnt.py

Fixed an error in the NA version

---

fgosccnt.py

As long as you use `self.exLogger` instead of plain logger, it will automatically prepend the target filename to each log message as follows:
```
$ ./fgosccnt.py ss/IMG_722*
__main__ <fgosccnt.py-L348> [INFO] [ss/IMG_7221.png] testing
__main__ <fgosccnt.py-L348> [INFO] [ss/IMG_7222.png] testing
__main__ <fgosccnt.py-L348> [INFO] [ss/IMG_7223.png] testing                                                                                                                                            __main__ <fgosccnt.py-L348> [INFO] [ss/IMG_7224.png] testing
__main__ <fgosccnt.py-L348> [INFO] [ss/IMG_7225.png] testing                                                                                                                                            __main__ <fgosccnt.py-L348> [INFO] …
```

introduce a custom logger that prepends the target filename to each log message

---

fgosccnt.py

Fixed misrecognition of item position in NA version

---

pageinfo.py

ポイント判別の閾値が15以下だと甘かったので1つ緩め16以下に設定

update pageinfo to the latest

---

pageinfo.py

左右に黒余白がある場合に pageinfo の行判定が誤動作する問題を修正。

---

pageinfo.py

pageinfo: improve detect_side_black_margin()

---

fgosccnt.py

#343 の対応
1. ノッチの判定幅を大きくした
2, iPad mini のノッチ付きスクリーンショットに対応した

fix for screenshot with notch

---

fgosccnt.py

#345 の修正
PNGファイルのOCRで誤認識がでるものがあるので、JPEGに使用していたルーチンを使うよう変更

Unify PNG reading routines with those for JPEG

---

csv2counter.py

今後新たなアイテムドロップアップ礼装が追加された場合はdrop_list に追加していけばよい

塵がドロップした場合「塵泥UP %」に対応

---

csv2counter.py
fgosccnt.py

Fix for no file

---

fgosccnt.py

複数ファイルが認識される場合で有効なファイルが0の場合の修正

Fix invalid multiple files

---

fgosccnt.py

#359 の修正
3行目のアイテムはitemとpointを結合した辞書でアイテムを判定

Fixed a bug where items were recognized as points

---

fgosccnt.py

fix missing page error

---

fgosccnt.py

自動変換種火誤認識の修正

---

csv2counter.py

csv2counter.py 警告の省略
